// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

edition = "2023";

package secure_aggregation.willow;

import "shell_encryption/rns/rns_serialization.proto";

option java_multiple_files = true;
option java_outer_classname = "CiphertextsProto";

message AhePublicKey {
  rlwe.SerializedRnsPolynomial ahe_public_key = 1;
}

message AheRecoveryCiphertext {
  repeated rlwe.SerializedRnsPolynomial ciphertext = 1;
}

message AhePartialDecCiphertext {
  repeated rlwe.SerializedRnsPolynomial ciphertext = 1;
}

message KaheCiphertext {
  repeated rlwe.SerializedRnsPolynomial ciphertext = 1;
}

message AhePartialDecryption {
  repeated rlwe.SerializedRnsPolynomial partial_decryption = 1;
}
